print(f"##############################")
print(f"#                            #")
print(f"#         Faris Ramadhan     #")
print(f"#         2610817210017      #")
print(f"#                            #")
print(f"##############################")